quantization:
  quantization_batch_size: 8
  calib_set_size: 64
  calib_set_name: null
  calib_batch_size: null
hn_editor:
  yuv2rgb: false
  input_resize:
    enabled: false
  channels_remove:
    enabled: false
  flip: false
  skip_connection_remove: null
  bgr2rgb: false
  output_scheme:
    change_activations:
      enabled: false
    integrated_postprocessing:
      enabled: false
      chains: []
    split_output: false
paths:
  alls_script: null
  hailo_archive_path: null
preprocessing:
  meta_arch: null
  centered: true
  input_shape: null
  max_pad: 100
  padding_color: 114
allocation:
  allocation_timeout: null
  max_elementwise_feed_repeat: 4
  required_fps: 1
parser:
  ew_add_policy: fused_conv_and_add
  nodes:
  - null
  - null
  start_node_shape: null
  is_tf2_saved_model: false
  normalization_params:
    normalize_in_net: false
    fold_normalization: false
    mean_list: null
    std_list: null
postprocessing:
  anchors:
    sizes: null
  meta_arch: null
  score_threshold: null
  nms_iou_thresh: null
  ext_upsample: null
  device_pre_post_layers:
    softmax: false
    argmax: false
    bilinear: false
    nms: false
    max_finder: false
  postprocess_config_json: null
evaluation:
  labels_offset: 0
  limit_num_images: 1000000000.0
  infer_type: tf_infer
  classes: 1
  two_stage_arch: false
  network_type: null
  gt_json_path: null
  labels_map: null
info:
  client_or_rnd: r&d
  standard_or_customized: standard
  task: N/A
  input_shape: N/A
  output_shape: N/A
  operations: N/A
  parameters: N/A
  framework: N/A
  training_data: N/A
  validation_data: N/A
  eval_metric: N/A
  full_precision_result: null
  source: N/A
  license_url: N/A
